<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Live Feed from the PHP-Nuke Platinum v7.6.5 PNPv3 Website</title>
<style type="text/css">
.version-bold {
}
</style>
</head>
<body> 
<div align="center"><strong>Current Build:</strong> 20940402282023 &nbsp;&nbsp;&nbsp;&nbsp;<strong>Current Version:</strong> 7.6.5</div>
<div align="center"><strong>PHP-Nuke Titanium Repsoitory</strong> (Nightly Builds)</div>
<div align="center"><a class="titaniumbutton" href="https://github.com/ernestbuffington/PNPv2" target="_blank"><i class="bi bi-github"></i> Visit GitHub Repository</a></div>
<br>
<hr>                                                                    
<strong><i class="bi bi-calendar-check"> </i><span class="bold-version" style="font-weight: bold; color: #0F0;">[ Feb 3rd, 2023 ] 7.6.b.4 -> 7.6.5b BETA</span></strong>   <br>
<i class="bi bi-backspace-reverse"></i> Ported Platinum Downloads for PHP 8.2.3                         <br>
<i class="bi bi-backspace-reverse"></i> Ported Platinum Theme Console for PHP 8.2.3                     <br>
<i class="bi bi-backspace-reverse"></i> Ported Platinum Theme Control Panel for PHP 8.2.3               <br>
<i class="bi bi-backspace-reverse"></i> Updated Database Layer for PHP 8.2.3                            <br>
<i class="bi bi-backspace-reverse"></i> Started Portinng Process for PHP 8.2.3                          <br>
<i class="bi bi-backspace-reverse"></i> Updated Amazon Module Patched for PHP 8.2.3                     <br>
<i class="bi bi-backspace-reverse"></i> Added Ruffle Support                                            <br>
<i class="bi bi-backspace-reverse"></i> New Installer Created                                           <br>
<i class="bi bi-backspace-reverse"></i> New Database Controller                                         <br>
<i class="bi bi-backspace-reverse"></i> New Zend Caching Syetem (Zf1)                                   <br>
<i class="bi bi-backspace-reverse"></i> New Google Site Map Module                                      <br>
<i class="bi bi-backspace-reverse"></i> New Blog System                                                 <br>
<i class="bi bi-backspace-reverse"></i> Added Bootstrap Support                                         <br>
<i class="bi bi-backspace-reverse"></i> New WYSIWYG System                                              <br>
<i class="bi bi-backspace-reverse"></i> Updated Sentinel                                                <br>
<i class="bi bi-backspace-reverse"></i> Added New Error Logging System                                  <br>
<i class="bi bi-backspace-reverse"></i> Added Ajax Support (Dran N' Drop)                               <br>
<i class="bi bi-backspace-reverse"></i> Updated Your Account Module                                     <br>
<i class="bi bi-backspace-reverse"></i> New Theme System (Supports XML/HTML all versions)               <br>
<i class="bi bi-backspace-reverse"></i> Added Admin Module Honeypot v2.2 by CoRpSE                      <br>
<i class="bi bi-backspace-reverse"></i> Added File Repository Module                                    <br>
<i class="bi bi-backspace-reverse"></i> Added Image Hosting Module                                      <br>
<i class="bi bi-backspace-reverse"></i> Added Mobile Detect Libraries                                   <br>
<i class="bi bi-backspace-reverse"></i> Added php81_bc/strftime Library                                 <br>
<i class="bi bi-backspace-reverse"></i> Added phpmailer/phpmailer v6.7.1 Library                        <br>
<i class="bi bi-backspace-reverse"></i> Added swiftmailer/swiftmailer v6.2 Library                      <br>
<i class="bi bi-backspace-reverse"></i> Added Symfony Mailer (Soon will replace Swiftmailer)            <br>
<i class="bi bi-backspace-reverse"></i> Added rector/rector root Libraries (refactoring)                <br>
<i class="bi bi-backspace-reverse"></i> Added Root / Composer Support                                   <br>
<i class="bi bi-backspace-reverse"></i> Added includes Composer Support                                 <br>
<i class="bi bi-backspace-reverse"></i> Added Network Support for The 86it Developers Network           <br>
<i class="bi bi-backspace-reverse"></i> Added New Menu Block (Replaces Sommaire)                        <br>
<i class="bi bi-backspace-reverse"></i> Added New Version Checking System                               <br>
<i class="bi bi-backspace-reverse"></i> Added Platinum Developer Feed to Admin Panel                    <br>
<hr>                                                                    
<strong><i class="bi bi-calendar-check"> </i><span class="bold-version" style="font-weight: bold; color: #0F0;">[ Dec 9th, 2005 ] 7.6.b.3 -> 7.6.b.4 BETA</span></strong>   <br>
<i class="bi bi-backspace-reverse"></i> Added the bbtonuke 2.0.19 update patch and fixes to date        <br>
<i class="bi bi-backspace-reverse"></i> Fixed security exploit within mainfile.php                      <br>
<i class="bi bi-backspace-reverse"></i> Removed games from arcade that would not submit high score      <br>
<i class="bi bi-backspace-reverse"></i> Updated Sentinel to pl1 patch                                   <br>
<i class="bi bi-backspace-reverse"></i> Readded Protector System with customized version to work in     <br>
<i class="bi bi-backspace-reverse"></i> unison with Sentinel                                            <br>
<i class="bi bi-backspace-reverse"></i> Fixed Admin Creation and User Promotion problem                 <br>
<i class="bi bi-backspace-reverse"></i> Updated Cash Mod settings                                       <br>
<i class="bi bi-backspace-reverse"></i> Added Admin Notepad for record keeping between Admins           <br>
<hr>                                                                    
<strong><i class="bi bi-calendar-check"> </i><span class="bold-version" style="font-weight: bold; color: #0F0;">[ Dec 9th, 2005 ] 7.6.b.2 -> 7.6.b.3 BETA</span></strong>   <br>
<i class="bi bi-backspace-reverse"></i> Updated PHPBB to 2.0.18 and added all new security updates      <br>
<i class="bi bi-backspace-reverse"></i> Updated Shout Box to 8.5                                        <br>
<i class="bi bi-backspace-reverse"></i> Added Arcade Tweaks                                             <br>
<i class="bi bi-backspace-reverse"></i> Fixed Group Assignment error in forums admin                    <br>
<i class="bi bi-backspace-reverse"></i> Replaced Protector with Sentinel 2.4.2                          <br>
<i class="bi bi-backspace-reverse"></i> Installed Advanced Backup system                                <br>
<i class="bi bi-backspace-reverse"></i> Fixed Cash Mod                                                  <br>
<i class="bi bi-backspace-reverse"></i> Added 230 games to the arcade                                   <br>
<i class="bi bi-backspace-reverse"></i> Advanced User Color member add problem fixed                    <br>
<i class="bi bi-backspace-reverse"></i> Fixed Hosting background code to draw from the theme added      <br>
<i class="bi bi-backspace-reverse"></i> Fixed Sticky and global post problem                            <br>
<i class="bi bi-backspace-reverse"></i> Fixed User promotion and Your account bug                       <br>
<i class="bi bi-backspace-reverse"></i> Updated Reviews Module to a working version                     <br>
<i class="bi bi-backspace-reverse"></i> Fixed Statistics module for Firefox stats                       <br>
<i class="bi bi-backspace-reverse"></i> Added Topic Reply with Message included Mod                     <br>
<i class="bi bi-backspace-reverse"></i> Fixed V2D Double Glance theme problem                           <br>
<i class="bi bi-backspace-reverse"></i> Added News Page Numbers Mod                                     <br>
<i class="bi bi-backspace-reverse"></i> Fixed Content Module                                            <br>
<i class="bi bi-backspace-reverse"></i> Updated Audio and Video Stream bbcode compatibility             <br>
<i class="bi bi-backspace-reverse"></i> Fixed Debug mode on forums admin                                <br>
<i class="bi bi-backspace-reverse"></i> Added compatability code to Mainfile.php for servers running    <br>
<i class="bi bi-backspace-reverse"></i> php as cgi which gave them access denied messages in Admin      <br>
<i class="bi bi-backspace-reverse"></i> Fix The XSS Exploit thanks to Technocrat                        <br>
<i class="bi bi-backspace-reverse"></i> Removed the Web bbcode function and button from all themes      <br>
<hr>                                                                    
<strong><i class="bi bi-calendar-check"> </i><span class="bold-version" style="font-weight: bold; color: #0F0;">[ Aug 1st, 2005 ] 7.6.b.1 -> 7.6.b.2 BETA</span></strong>   <br>
<i class="bi bi-backspace-reverse"></i> Updated PHPBB to 2.0.17 and added all new security updates      <br>
<i class="bi bi-backspace-reverse"></i> Fixed Shout Box table problem thanks to Althatinny              <br>
<i class="bi bi-backspace-reverse"></i> Fixed Arcade Error                                              <br>
<i class="bi bi-backspace-reverse"></i> Fixed Banners Ads                                               <br>
<i class="bi bi-backspace-reverse"></i> Fixed Log Moderators Action Addon                               <br>
<i class="bi bi-backspace-reverse"></i> Fixed Theme System                                              <br>
<i class="bi bi-backspace-reverse"></i> Added Thank You and Cancel Modules for use with Donations Module<br>
<hr>                                                                    
<strong><i class="bi bi-calendar-check"> </i><span class="bold-version" style="font-weight: bold; color: #0F0;">[ July 1st, 2005 ] 7.6.0 -> 7.6.b.1 BETA</span></strong>   <br>
<i class="bi bi-backspace-reverse"></i> Updated PHPBB to 2.0.16 added all security updates             <br>
<i class="bi bi-backspace-reverse"></i> Updated the Your Account Module to 4.4.2                       <br>
<i class="bi bi-backspace-reverse"></i> Updated the Shout Box to Version 6.02                          <br>
<i class="bi bi-backspace-reverse"></i> Addedd over 100 Avatars                                        <br>
<i class="bi bi-backspace-reverse"></i> Updated Arcade and Added over 30 games preinstalled            <br>
<i class="bi bi-backspace-reverse"></i> Corrected BBCode Gradient                                      <br>
<i class="bi bi-backspace-reverse"></i> Corrected BBCode Helpline                                      <br>
<i class="bi bi-backspace-reverse"></i> Corrected BBCode Java                                          <br>
<i class="bi bi-backspace-reverse"></i> Corrected BBCode PHP                                           <br>
<i class="bi bi-backspace-reverse"></i> Corrected BBGroups SQL                                         <br>
<i class="bi bi-backspace-reverse"></i> Corrected Block Modularity Function                            <br>
<i class="bi bi-backspace-reverse"></i> Corrected Blocks SQL                                           <br>
<i class="bi bi-backspace-reverse"></i> Corrected Config SQL                                           <br>
<i class="bi bi-backspace-reverse"></i> Corrected Content Edit Function                                <br>
<i class="bi bi-backspace-reverse"></i> Corrected Counter SQL                                          <br>
<i class="bi bi-backspace-reverse"></i> Corrected Display Error SQL                                    <br>
<i class="bi bi-backspace-reverse"></i> Corrected Logging SQL                                          <br>
<i class="bi bi-backspace-reverse"></i> Corrected Platinum Technology SQL                              <br>
<i class="bi bi-backspace-reverse"></i> Corrected Shout Box Java Source                                <br>
<i class="bi bi-backspace-reverse"></i> Corrected Theme System SQL                                     <br>
<i class="bi bi-backspace-reverse"></i> Corrected Universal Administration                             <br>
<i class="bi bi-backspace-reverse"></i> Corrected Users SQL                                            <br>
<i class="bi bi-backspace-reverse"></i> Corrected Your Account Private Message Plug                    <br>
<i class="bi bi-backspace-reverse"></i> Secured Work Board                                             <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Admin Submissions W3C Compliance                      <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Admin Navigation W3C Compliance                       <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Administrative W3C Compliance                         <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Big Story Of Today W3C Compliance                     <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Docs W3C Compliance                                   <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Hosting Administration W3C Compliance                 <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Installation W3C Compliance                           <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Navigation W3C Compliance                             <br>
<i class="bi bi-backspace-reverse"></i> Upgraded News Administration                                   <br>
<i class="bi bi-backspace-reverse"></i> Upgraded News W3C Compliance                                   <br>
<i class="bi bi-backspace-reverse"></i> Upgraded PHP-Nuke Tools W3C Compliance                         <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Sentinel Patch Level                                  <br>
<i class="bi bi-backspace-reverse"></i> Upgraded SQL                                                   <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Subscription W3C Compliance                           <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Theme Conversion                                      <br>
<i class="bi bi-backspace-reverse"></i> Upgraded T-Platinum W3C Compliance                             <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Universal Administration W3C Compliance               <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Universal Language                                    <br>
<i class="bi bi-backspace-reverse"></i> Upgraded User Information W3C Compliance                       <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Who Is Online W3C Compliance                          <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Your Account Administration W3C Compliance            <br>
<hr>                                                                    
<strong><i class="bi bi-calendar-check"> </i><span class="bold-version" style="font-weight: bold; color: #0F0;">[ March 1st, 2005 ] 7.6.0.9 -> 7.6.b BETA</span></strong>   <br>
<i class="bi bi-backspace-reverse"></i> Added Action Logging                                           <br>
<i class="bi bi-backspace-reverse"></i> Added Common Replies                                           <br>
<i class="bi bi-backspace-reverse"></i> Added Custom Head                                              <br>
<i class="bi bi-backspace-reverse"></i> Added Double Post Control                                      <br>
<i class="bi bi-backspace-reverse"></i> Added Error Display Switch                                     <br>
<i class="bi bi-backspace-reverse"></i> Added Function URLAdmin                                        <br>
<i class="bi bi-backspace-reverse"></i> Added Glance Advanced Username Colour Compatibility            <br>
<i class="bi bi-backspace-reverse"></i> Added Original Banners                                         <br>
<i class="bi bi-backspace-reverse"></i> Added PHP-Nuke Index URL                                       <br>
<i class="bi bi-backspace-reverse"></i> Added Secure Version Check                                     <br>
<i class="bi bi-backspace-reverse"></i> Added Theme System                                             <br>
<i class="bi bi-backspace-reverse"></i> Added Theme Conversion Upgrade                                 <br>
<i class="bi bi-backspace-reverse"></i> Added Users Custom Box                                         <br>
<i class="bi bi-backspace-reverse"></i> Added 7.6.0 Upgrade Ability                                    <br>
<i class="bi bi-backspace-reverse"></i> Corrected 691-760 SQL                                          <br>
<i class="bi bi-backspace-reverse"></i> Corrected Acronym BBCode                                       <br>
<i class="bi bi-backspace-reverse"></i> Corrected Administration Indentation                           <br>
<i class="bi bi-backspace-reverse"></i> Corrected Avatar Screen Width                                  <br>
<i class="bi bi-backspace-reverse"></i> Corrected Arcade Strings                                       <br>
<i class="bi bi-backspace-reverse"></i> Corrected Arcade Check                                         <br>
<i class="bi bi-backspace-reverse"></i> Corrected Arcade Default Config                                <br>
<i class="bi bi-backspace-reverse"></i> Corrected Attachment Download                                  <br>
<i class="bi bi-backspace-reverse"></i> Corrected Author Search                                        <br>
<i class="bi bi-backspace-reverse"></i> Corrected Ban Request Language                                 <br>
<i class="bi bi-backspace-reverse"></i> Corrected Block Administration Abstraction                     <br>
<i class="bi bi-backspace-reverse"></i> Corrected Classifeds Permissions                               <br>
<i class="bi bi-backspace-reverse"></i> Corrected Constants Comments                                   <br>
<i class="bi bi-backspace-reverse"></i> Corrected Cookies                                              <br>
<i class="bi bi-backspace-reverse"></i> Corrected Database Restoration                                 <br>
<i class="bi bi-backspace-reverse"></i> Corrected Documentation                                        <br>
<i class="bi bi-backspace-reverse"></i> Corrected Edit User Cosmetic                                   <br>
<i class="bi bi-backspace-reverse"></i> Corrected Forum Avatar Management                              <br>
<i class="bi bi-backspace-reverse"></i> Corrected Forum Globals                                        <br>
<i class="bi bi-backspace-reverse"></i> Corrected Forum Queries                                        <br>
<i class="bi bi-backspace-reverse"></i> Corrected Forum Search                                         <br>
<i class="bi bi-backspace-reverse"></i> Corrected Glance URL                                           <br>
<i class="bi bi-backspace-reverse"></i> Corrected GZip Detection                                       <br>
<i class="bi bi-backspace-reverse"></i> Corrected Illegal Extension                                    <br>
<i class="bi bi-backspace-reverse"></i> Corrected Illegal Path Disclosures                             <br>
<i class="bi bi-backspace-reverse"></i> Corrected Journal Entities                                     <br>
<i class="bi bi-backspace-reverse"></i> Corrected Mailing List Email Function                          <br>
<i class="bi bi-backspace-reverse"></i> Corrected Protector System Cosmetics                           <br>
<i class="bi bi-backspace-reverse"></i> Corrected Ranks URL Properties                                 <br>
<i class="bi bi-backspace-reverse"></i> Corrected Related Negative Return                              <br>
<i class="bi bi-backspace-reverse"></i> Corrected Report TPL                                           <br>
<i class="bi bi-backspace-reverse"></i> Corrected Search Variables                                     <br>
<i class="bi bi-backspace-reverse"></i> Corrected Sort Submission                                      <br>
<i class="bi bi-backspace-reverse"></i> Corrected Statistics Firefox Recognise                         <br>
<i class="bi bi-backspace-reverse"></i> Corrected Theme Selection                                      <br>
<i class="bi bi-backspace-reverse"></i> Corrected Topic Notify Posted Message                          <br>
<i class="bi bi-backspace-reverse"></i> Corrected Unread Posts Redirection                             <br>
<i class="bi bi-backspace-reverse"></i> Corrected Upgrade SQL Counter                                  <br>
<i class="bi bi-backspace-reverse"></i> Corrected View Online URL Location                             <br>
<i class="bi bi-backspace-reverse"></i> Corrected X5 Timezones                                         <br>
<i class="bi bi-backspace-reverse"></i> Corrected Your Account Field Addition Syntax                   <br>
<i class="bi bi-backspace-reverse"></i> Corrected Your Account Fixtext Function                        <br>
<i class="bi bi-backspace-reverse"></i> Corrected Your Account Registration String                     <br>
<i class="bi bi-backspace-reverse"></i> Removed Duplicate File                                         <br>
<i class="bi bi-backspace-reverse"></i> Removed Supplementary News                                     <br>
<i class="bi bi-backspace-reverse"></i> Secured All Administration Files                               <br>
<i class="bi bi-backspace-reverse"></i> Secured All Block Files                                        <br>
<i class="bi bi-backspace-reverse"></i> Secured All Desolate Files                                     <br>
<i class="bi bi-backspace-reverse"></i> Secured All Module Files                                       <br>
<i class="bi bi-backspace-reverse"></i> Secured Attachment Download                                    <br>
<i class="bi bi-backspace-reverse"></i> Secured Banners                                                <br>
<i class="bi bi-backspace-reverse"></i> Secured FAQ                                                    <br>
<i class="bi bi-backspace-reverse"></i> Secured Feedback                                               <br>
<i class="bi bi-backspace-reverse"></i> Secured Journal                                                <br>
<i class="bi bi-backspace-reverse"></i> Secured Mainfile                                               <br>
<i class="bi bi-backspace-reverse"></i> Secured phpBB HTTP Post Variables                              <br>
<i class="bi bi-backspace-reverse"></i> Tweaked Engine Performance x25%                                <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Advanced Username Colour                              <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Banner Ads                                            <br>
<i class="bi bi-backspace-reverse"></i> Upgraded BBCode Box Browser Compatbility                       <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Block Modularity Engine                               <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Center Blocks                                         <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Classifeds                                            <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Contact Plus                                          <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Group Downloads                                       <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Language                                              <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Mailing List                                          <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Mainfile Functions                                    <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Module Administrative Links                           <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Modules Modularity Engine                             <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Navigation Block                                      <br>
<i class="bi bi-backspace-reverse"></i> Upgraded phpBB                                                 <br>
<i class="bi bi-backspace-reverse"></i> Upgraded PHP-Nuke Patched                                      <br>
<i class="bi bi-backspace-reverse"></i> Upgraded RPG Races                                             <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Script Depository                                     <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Shout Box                                             <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Supporters                                            <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Work Board                                            <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Work Probe                                            <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Work Request                                          <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Your Account                                          <br>
<hr>                                                                    
<strong><i class="bi bi-calendar-check"> </i><span class="bold-version" style="font-weight: bold; color: #0F0;">[ Deccember 25th, 2004 ] 7.6.0.1 BETA -> 7.6.0.9</span></strong>   <br>
<i class="bi bi-backspace-reverse"></i> Released Public Final                                          <br>
<i class="bi bi-backspace-reverse"></i> Secured Admin Links                                            <br>
<i class="bi bi-backspace-reverse"></i> Secured Header.php                                             <br>
<i class="bi bi-backspace-reverse"></i> Secured Mainfile.php                                           <br>
<i class="bi bi-backspace-reverse"></i> Secured News Comments                                          <br>
<i class="bi bi-backspace-reverse"></i> Secured NBBCode.php                                            <br>
<i class="bi bi-backspace-reverse"></i> Secured Survey Comments                                        <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Credits                                               <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Force Word Wrapping                                   <br>
<i class="bi bi-backspace-reverse"></i> Upgraded PHP-Nuke Patched                                      <br>
<i class="bi bi-backspace-reverse"></i> Upgraded SQL Install                                           <br>
<i class="bi bi-backspace-reverse"></i> Upgraded SQL Upgrade                                           <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Supplementary                                         <br>
<i class="bi bi-backspace-reverse"></i> Upgraded Theme Conversion                                      <br>
<hr>
<strong><i class="bi bi-calendar-check"> </i><span class="bold-version" style="font-weight: bold; color: #0F0;">[ November 24th, 2004 ] 7.5.0.1 BETA -> 7.6.0.1 BETA</span></strong>   <br>
<i class="bi bi-backspace-reverse"></i> Added Admin File Editability                                   <br>
<i class="bi bi-backspace-reverse"></i> Added Authors Check                                            <br>
<i class="bi bi-backspace-reverse"></i> Added Custom File Folder                                       <br>
<i class="bi bi-backspace-reverse"></i> Added FireFox Support                                          <br>
<i class="bi bi-backspace-reverse"></i> Added Install Block                                            <br>
<i class="bi bi-backspace-reverse"></i> Added RSS FireFox Feed Support                                 <br>
<i class="bi bi-backspace-reverse"></i> Corrected Administrator Edit Function                          <br>
<i class="bi bi-backspace-reverse"></i> Corrected Anoymous Permissions                                 <br>
<i class="bi bi-backspace-reverse"></i> Corrected Attachment Access Data                               <br>
<i class="bi bi-backspace-reverse"></i> Corrected Banner Ads / Firewall                                <br>
<i class="bi bi-backspace-reverse"></i> Corrected Buddy List                                           <br>
<i class="bi bi-backspace-reverse"></i> Corrected Chat Blocks DB Connection                            <br>
<i class="bi bi-backspace-reverse"></i> Corrected Cookie SubDomain Admin Access                        <br>
<i class="bi bi-backspace-reverse"></i> Corrected Forum Admin Index URL                                <br>
<i class="bi bi-backspace-reverse"></i> Corrected Forums Administration Redirection                    <br>
<i class="bi bi-backspace-reverse"></i> Corrected ForumNews BBStuff                                    <br>
<i class="bi bi-backspace-reverse"></i> Corrected Forum Rules Language                                 <br>
<i class="bi bi-backspace-reverse"></i> Corrected Forum Search Results                                 <br>
<i class="bi bi-backspace-reverse"></i> Corrected GPL Issues                                           <br>
<i class="bi bi-backspace-reverse"></i> Corrected Jump Box                                             <br>
<i class="bi bi-backspace-reverse"></i> Corrected Overall Header Redirection                           <br>
<i class="bi bi-backspace-reverse"></i> Corrected phpBB Profile                                        <br>
<i class="bi bi-backspace-reverse"></i> Corrected PHP-Nuke Tools Cosmetic                              <br>
<i class="bi bi-backspace-reverse"></i> Corrected Points Function                                      <br>
<i class="bi bi-backspace-reverse"></i> Corrected Protector System Cosmetic                            <br>
<i class="bi bi-backspace-reverse"></i> Corrected Sections Migration                                   <br>
<i class="bi bi-backspace-reverse"></i> Corrected Shopping Cart Permissions                            <br>
<i class="bi bi-backspace-reverse"></i> Corrected Shout Box Scripting                                  <br>
<i class="bi bi-backspace-reverse"></i> Corrected Shout Box Smilies                                    <br>
<i class="bi bi-backspace-reverse"></i> Corrected Signature Preview / Save                             <br>
<i class="bi bi-backspace-reverse"></i> Corrected Smilie Statistics                                    <br>
<i class="bi bi-backspace-reverse"></i> Corrected Supplementary                                        <br>
<i class="bi bi-backspace-reverse"></i> Corrected User Author Promotion                                <br>
<i class="bi bi-backspace-reverse"></i> Corrected Your Account Activation Status                       <br>
<i class="bi bi-backspace-reverse"></i> Removed My_Header.php                                          <br>
<i class="bi bi-backspace-reverse"></i> Secured Admin.php                                              <br>
<i class="bi bi-backspace-reverse"></i> Secured Config.php                                             <br>
<i class="bi bi-backspace-reverse"></i> Secured Mainfile.php                                           <br>
<i class="bi bi-backspace-reverse"></i> Upgraded phpBB 2.0.11                                          <br>
<i class="bi bi-backspace-reverse"></i> Upgraded PHP-Nuke 7.6                                          <br>
<hr>
<strong><i class="bi bi-calendar-check"> </i><span class="bold-version" style="font-weight: bold; color: #0F0;">[ November 17th, 2004 ] 7.5.0.1 BETA</span></strong>   <br>
<i class="bi bi-backspace-reverse"></i> Added Acronym                                                  <br>
<i class="bi bi-backspace-reverse"></i> Added Admin Cookie Checks                                      <br>
<i class="bi bi-backspace-reverse"></i> Added Admin Manage Topic Shadows                               <br>
<i class="bi bi-backspace-reverse"></i> Added Admin Private Message Manager                            <br>
<i class="bi bi-backspace-reverse"></i> Added Admin User List                                          <br>
<i class="bi bi-backspace-reverse"></i> Added Admin Voting                                             <br>
<i class="bi bi-backspace-reverse"></i> Added Advanced Report                                          <br>
<i class="bi bi-backspace-reverse"></i> Added Advanced Signature Divider                               <br>
<i class="bi bi-backspace-reverse"></i> Added Advanced Staff                                           <br>
<i class="bi bi-backspace-reverse"></i> Added Advanced Username Colour                                 <br>
<i class="bi bi-backspace-reverse"></i> Added Album                                                    <br>
<i class="bi bi-backspace-reverse"></i> Added Arcade                                                   <br>
<i class="bi bi-backspace-reverse"></i> Added At A Glance                                              <br>
<i class="bi bi-backspace-reverse"></i> Added Ban Request                                              <br>
<i class="bi bi-backspace-reverse"></i> Added Banner Ads                                               <br>
<i class="bi bi-backspace-reverse"></i> Added BBCode Box                                               <br>
<i class="bi bi-backspace-reverse"></i> Added Block Album                                              <br>
<i class="bi bi-backspace-reverse"></i> Added Block Banner Ads                                         <br>
<i class="bi bi-backspace-reverse"></i> Added Block Calendar                                           <br>
<i class="bi bi-backspace-reverse"></i> Added Block Chat                                               <br>
<i class="bi bi-backspace-reverse"></i> Added Block Classifeds                                         <br>
<i class="bi bi-backspace-reverse"></i> Added Block Donations                                          <br>
<i class="bi bi-backspace-reverse"></i> Added Block Expiration                                         <br>
<i class="bi bi-backspace-reverse"></i> Added Block Google Counter                                     <br>
<i class="bi bi-backspace-reverse"></i> Added Block Server Information                                 <br>
<i class="bi bi-backspace-reverse"></i> Added Block Shopping Cart                                      <br>
<i class="bi bi-backspace-reverse"></i> Added Block Shout Box                                          <br>
<i class="bi bi-backspace-reverse"></i> Added Block Supporters                                         <br>
<i class="bi bi-backspace-reverse"></i> Added Block Tools                                              <br>
<i class="bi bi-backspace-reverse"></i> Added Block Top Referers                                       <br>
<i class="bi bi-backspace-reverse"></i> Added Block Top Sites                                          <br>
<i class="bi bi-backspace-reverse"></i> Added Block Total Hits                                         <br>
<i class="bi bi-backspace-reverse"></i> Added Block Universal                                          <br>
<i class="bi bi-backspace-reverse"></i> Added Block Web Links                                          <br>
<i class="bi bi-backspace-reverse"></i> Added Block Work Board                                         <br>
<i class="bi bi-backspace-reverse"></i> Added Bottom Aligned Signatures                                <br>
<i class="bi bi-backspace-reverse"></i> Added Buddy List                                               <br>
<i class="bi bi-backspace-reverse"></i> Added Calendar                                                 <br>
<i class="bi bi-backspace-reverse"></i> Added Center Blocks                                            <br>
<i class="bi bi-backspace-reverse"></i> Added Chat                                                     <br>
<i class="bi bi-backspace-reverse"></i> Added Classifeds                                               <br>
<i class="bi bi-backspace-reverse"></i> Added CNB Your Account                                         <br>
<i class="bi bi-backspace-reverse"></i> Added Conditional Blocks                                       <br>
<i class="bi bi-backspace-reverse"></i> Added Contact Plus                                             <br>
<i class="bi bi-backspace-reverse"></i> Added Content BBCode                                           <br>
<i class="bi bi-backspace-reverse"></i> Added Cosmetic Administration Interface                        <br>
<i class="bi bi-backspace-reverse"></i> Added Cosmetic Articles                                        <br>
<i class="bi bi-backspace-reverse"></i> Added Cosmetic BBCode                                          <br>
<i class="bi bi-backspace-reverse"></i> Added Cosmetic Default Avatar                                  <br>
<i class="bi bi-backspace-reverse"></i> Added Cosmetic Downloads                                       <br>
<i class="bi bi-backspace-reverse"></i> Added Cosmetic Images Directory                                <br>
<i class="bi bi-backspace-reverse"></i> Added Cosmetic Journal                                         <br>
<i class="bi bi-backspace-reverse"></i> Added Cosmetic Ranks                                           <br>
<i class="bi bi-backspace-reverse"></i> Added Cosmetic Smilies                                         <br>
<i class="bi bi-backspace-reverse"></i> Added Cosmetic Statistics                                      <br>
<i class="bi bi-backspace-reverse"></i> Added Cosmetic T-Platinum                                      <br>
<i class="bi bi-backspace-reverse"></i> Added Cosmetic Topic Icons                                     <br>
<i class="bi bi-backspace-reverse"></i> Added Cosmetic Your Account                                    <br>
<i class="bi bi-backspace-reverse"></i> Added Database Backup                                          <br>
<i class="bi bi-backspace-reverse"></i> Added Disallow Edit Admin Posts                                <br>
<i class="bi bi-backspace-reverse"></i> Added Disallow Rule                                            <br>
<i class="bi bi-backspace-reverse"></i> Added Edit User Post Count                                     <br>
<i class="bi bi-backspace-reverse"></i> Added Emporium                                                 <br>
<i class="bi bi-backspace-reverse"></i> Added Enhanced Downloads                                       <br>
<i class="bi bi-backspace-reverse"></i> Added FAQ Editor                                               <br>
<i class="bi bi-backspace-reverse"></i> Added ForumNews Advance                                        <br>
<i class="bi bi-backspace-reverse"></i> Added Force Word Wrapping                                      <br>
<i class="bi bi-backspace-reverse"></i> Added File Attachment                                          <br>
<i class="bi bi-backspace-reverse"></i> Added Google Counter                                           <br>
<i class="bi bi-backspace-reverse"></i> Added Global Announcement                                      <br>
<i class="bi bi-backspace-reverse"></i> Added IntelliCencor                                            <br>
<i class="bi bi-backspace-reverse"></i> Added IP Ban System                                            <br>
<i class="bi bi-backspace-reverse"></i> Added IP Whois Lookup                                          <br>
<i class="bi bi-backspace-reverse"></i> Added Keep it Moving                                           <br>
<i class="bi bi-backspace-reverse"></i> Added Legal Docs                                               <br>
<i class="bi bi-backspace-reverse"></i> Added List Smilies Per Post                                    <br>
<i class="bi bi-backspace-reverse"></i> Added Lock Topic After Post                                    <br>
<i class="bi bi-backspace-reverse"></i> Added Merge Topics                                             <br>
<i class="bi bi-backspace-reverse"></i> Added Move Topics Locked                                       <br>
<i class="bi bi-backspace-reverse"></i> Added Navigation / Module                                      <br>
<i class="bi bi-backspace-reverse"></i> Added MReviews                                                 <br>
<i class="bi bi-backspace-reverse"></i> Added Numerical Checks                                         <br>
<i class="bi bi-backspace-reverse"></i> Added New Administration Permission System                     <br>
<i class="bi bi-backspace-reverse"></i> Added Groups                                                   <br>
<i class="bi bi-backspace-reverse"></i> Added Overall Permissions                                      <br>
<i class="bi bi-backspace-reverse"></i> Added PHP-Nuke Admin Link                                      <br>
<i class="bi bi-backspace-reverse"></i> Added PHP-Nuke Tools                                           <br>
<i class="bi bi-backspace-reverse"></i> Added Points Based User Groups                                 <br>
<i class="bi bi-backspace-reverse"></i> Added Points System                                            <br>
<i class="bi bi-backspace-reverse"></i> Added Private Messaage Quick Reply                             <br>
<i class="bi bi-backspace-reverse"></i> Added Printable Page                                           <br>
<i class="bi bi-backspace-reverse"></i> Added Rank List Advanced                                       <br>
<i class="bi bi-backspace-reverse"></i> Added Reduce ACP Navigation                                    <br>
<i class="bi bi-backspace-reverse"></i> Added Restrict Signatures                                      <br>
<i class="bi bi-backspace-reverse"></i> Added Search Form                                              <br>
<i class="bi bi-backspace-reverse"></i> Added Search Pacakge                                           <br>
<i class="bi bi-backspace-reverse"></i> Added Select Expand                                            <br>
<i class="bi bi-backspace-reverse"></i> Added Server Viewer                                            <br>
<i class="bi bi-backspace-reverse"></i> Added Shout Box                                                <br>
<i class="bi bi-backspace-reverse"></i> Added Show Smilies in Topic Title                              <br>
<i class="bi bi-backspace-reverse"></i> Added Signature Editor Preview Deluxe                          <br>
<i class="bi bi-backspace-reverse"></i> Added Signature Once Per Page                                  <br>
<i class="bi bi-backspace-reverse"></i> Added Smilies List                                             <br>
<i class="bi bi-backspace-reverse"></i> Added Sommaire Parametrable                                    <br>
<i class="bi bi-backspace-reverse"></i> Added Split Topic Type                                         <br>
<i class="bi bi-backspace-reverse"></i> Added Statistics                                               <br>
<i class="bi bi-backspace-reverse"></i> Added Staff                                                    <br>
<i class="bi bi-backspace-reverse"></i> Added Subscribed Users Block                                   <br>
<i class="bi bi-backspace-reverse"></i> Added Subscription System                                      <br>
<i class="bi bi-backspace-reverse"></i> Added Super Quick Reply                                        <br>
<i class="bi bi-backspace-reverse"></i> Added Supporters                                               <br>
<i class="bi bi-backspace-reverse"></i> Added Syntax Highlighting                                      <br>
<i class="bi bi-backspace-reverse"></i> Added Thread Kicker                                            <br>
<i class="bi bi-backspace-reverse"></i> Added Topic Jump                                               <br>
<i class="bi bi-backspace-reverse"></i> Added Topic Notify with Message Text                           <br>
<i class="bi bi-backspace-reverse"></i> Added Top Sites                                                <br>
<i class="bi bi-backspace-reverse"></i> Added Treasury                                                 <br>
<i class="bi bi-backspace-reverse"></i> Added Union Tap                                                <br>
<i class="bi bi-backspace-reverse"></i> Added Universal                                                <br>
<i class="bi bi-backspace-reverse"></i> Added User Cookie Checks                                       <br>
<i class="bi bi-backspace-reverse"></i> Added User Online Status                                       <br>
<i class="bi bi-backspace-reverse"></i> Added View Attachments                                         <br>
<i class="bi bi-backspace-reverse"></i> Added Web Links                                                <br>
<i class="bi bi-backspace-reverse"></i> Added Work Board                                               <br>
<i class="bi bi-backspace-reverse"></i> Added Whos Online                                              <br>
<i class="bi bi-backspace-reverse"></i> Added Who is Online Time                                       <br>
<i class="bi bi-backspace-reverse"></i> Corrected Admin.php                                            <br>
<i class="bi bi-backspace-reverse"></i> Corrected Authors Counter                                      <br>
<i class="bi bi-backspace-reverse"></i> Corrected Banners.php                                          <br>
<i class="bi bi-backspace-reverse"></i> Corrected Banners System                                       <br>
<i class="bi bi-backspace-reverse"></i> Corrected Blocks Administration                                <br>
<i class="bi bi-backspace-reverse"></i> Corrected Encyclopedia Module                                  <br>
<i class="bi bi-backspace-reverse"></i> Corrected Forum Language                                       <br>
<i class="bi bi-backspace-reverse"></i> Corrected Languages                                            <br>
<i class="bi bi-backspace-reverse"></i> Corrected Mainfile.php                                         <br>
<i class="bi bi-backspace-reverse"></i> Corrected Private Messages Module                              <br>
<i class="bi bi-backspace-reverse"></i> Corrected Review Module                                        <br>
<i class="bi bi-backspace-reverse"></i> Corrected SQL Injections                                       <br>
<i class="bi bi-backspace-reverse"></i> Corrected Search Module                                        <br>
<i class="bi bi-backspace-reverse"></i> Corrected Statistics Module                                    <br>
<i class="bi bi-backspace-reverse"></i> Corrected Subscribers Module                                   <br>
<i class="bi bi-backspace-reverse"></i> Corrected Survey Module                                        <br>
<i class="bi bi-backspace-reverse"></i> Corrected Surveys Block                                        <br>
<i class="bi bi-backspace-reverse"></i> Corrected User Info Blocks                                     <br>
<i class="bi bi-backspace-reverse"></i> Corrected Variables                                            <br>
<i class="bi bi-backspace-reverse"></i> Corrected Web Links Module                                     <br>
<i class="bi bi-backspace-reverse"></i> Corrected Your Account Module                                  <br>
<i class="bi bi-backspace-reverse"></i> Increased Session Length                                       <br>
<i class="bi bi-backspace-reverse"></i> Improved Administration System                                 <br>
<i class="bi bi-backspace-reverse"></i> Improved Modules Administration                                <br>
<i class="bi bi-backspace-reverse"></i> Improved Page Generation Values                                <br>
<i class="bi bi-backspace-reverse"></i> Removed Addon_Sample Module                                    <br>
<i class="bi bi-backspace-reverse"></i> Removed All Themes, Except T-Platinum                          <br>
<i class="bi bi-backspace-reverse"></i> Removed Amazon Related Files                                   <br>
<i class="bi bi-backspace-reverse"></i> Removed Auth.php                                               <br>
<i class="bi bi-backspace-reverse"></i> Removed Ephemerids Module                                      <br>
<i class="bi bi-backspace-reverse"></i> Removed Reviews                                                <br>
<i class="bi bi-backspace-reverse"></i> Removed Sections Module                                        <br>
<i class="bi bi-backspace-reverse"></i> Removed Statistics Version                                     <br>
<i class="bi bi-backspace-reverse"></i> Removed WebMail Module                                         <br>
<i class="bi bi-backspace-reverse"></i> Secured Admin.php                                              <br>
<i class="bi bi-backspace-reverse"></i> Secured Header.php                                             <br>
<i class="bi bi-backspace-reverse"></i> Secured Mainfile.php                                           <br>
<i class="bi bi-backspace-reverse"></i> Security Directory Protection                                  <br>
<i class="bi bi-backspace-reverse"></i> Security Forum Admin                                           <br>
<i class="bi bi-backspace-reverse"></i> Security PHP-Nuke Patched                                      <br>
<i class="bi bi-backspace-reverse"></i> Security Protector System                                      <br>
<i class="bi bi-backspace-reverse"></i> Security T-Console                                             <br>
<i class="bi bi-backspace-reverse"></i> Tweaked Groups                                                 <br>
<i class="bi bi-backspace-reverse"></i> Tweaked Members List                                           <br>
<i class="bi bi-backspace-reverse"></i> Tweaked Web Links                                              <br>
<i class="bi bi-backspace-reverse"></i> Upgraded phpBB 2.0.10                                          <br>
<i class="bi bi-backspace-reverse"></i> Upgraded PHP-Nuke 7.5                                          <br>
<hr>                                                                                                   
The New PHP-Nuke Platinum 7.6.5 PNPv3 package was created by TheGhost (Ernest Allen Buffington)       <br>
 Copyright (c) 2023 by Brandon Maintenance Management, LLC            <br>
 Core Developer - Graeme Allan                                        <br>
 Core Developer - Ernest Allen Buffington                             <br> 
<hr>                                                                 
 Original Platinum 7.6 package was created by TechGfX                 <br>
 Copyright (c) 2004 - 2006 by http://www.techgfx.com                  <br>
 Graeme Allan - Techgfx (goose@techgfx.com)                           <br>
<hr>                                                                  
His old webiste was Nukeplanet.com, old version of Platinum 7.6.b.3  <br>
 Scott Partee - <span class="loki">Loki</span> http://www.nukeplanet.com (loki@nukeplanet.com <br>
                                                                      <br>
 TechGFX: Your dreams, Our imagination                                <br>
 The PHP-Nuke Platinum Group: It takes a Village or A Savant!         <br>
<hr>
</body>
</html>