<?php
#### Generated by Html to PHP converter By Disipal Site (www.disipal.net) ####


echo"<TABLE WIDTH=\"100%\" HEIGHT=\"172\" BORDER=\"0\" CELLPADDING=\"0\" CELLSPACING=\"0\" background=\"themes/Mech/images/fm.jpg\">"
  . "  <!--DWLayoutTable-->"
  . "  <TR> "
  . "    <TD WIDTH=\"244\" HEIGHT=\"175\" COLSPAN=\"1\" ROWSPAN=\"1\" valign=\"top\"><table width=\"244\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"themes/Mech/images/fl.jpg\">"
  . "        <!--DWLayoutTable-->"
  . "        <tr> "
  . "          <td width=\"72\" height=\"49\">&nbsp;</td>"
  . "          <td width=\"122\">&nbsp;</td>"
  . "          <td width=\"50\">&nbsp;</td>"
  . "        </tr>"
  . "        <tr>"
  . "          <td height=\"103\">&nbsp;</td>"
  . "          <td valign=\"top\"><font color=\"#FFCC00\">$showdl</font></td>"
  . "          <td>&nbsp;</td>"
  . "        </tr>"
  . "        <tr>"
  . "          <td height=\"23\">&nbsp;</td>"
  . "          <td>&nbsp;</td>"
  . "          <td>&nbsp;</td>"
  . "        </tr>"
  . "      </table></TD>"
  . "    <TD WIDTH=\"100%\" align=\"center\" valign=\"top\"><img src=\"themes/Mech/images/fmm.jpg\" width=\"311\" height=\"175\"></TD>"
  . "    <TD WIDTH=\"240\" valign=\"top\"> <img src=\"themes/Mech/images/fr.jpg\" width=\"240\" height=\"175\"></TD>"
  . "  </TR><tr><td height=\"1\"><img src=\"themes/Mech/images/spacer.gif\" alt=\"\" width=\"244\" height=\"1\"></td><td></td><td><img src=\"themes/Mech/images/spacer.gif\" alt=\"\" width=\"240\" height=\"1\"></td></tr>"
  . "</TABLE>"
 ."";

?>
